.gitignore
CONTRIBUTING.md

Postgresql build process creates .deps subdirectories to place dependency files. Such directory should be filtered out.

Added .deps filter in .gitignore

---

Makefile
doc/functions.sgm
epochprop.c
epochprop.h
expected/epochprop.out
pgs_epochprop.sql.in
sql/epochprop.sql
vector3d.c
vector3d.h

This PR lays the basis for pg_sphere-based functions for
epoch-propagating positions (i.e., compute their positions, proper
motions, parallaxes and radial velocities after some time based on their
values at epoch X under the assumption of linear motion).
This largely follows what is implemented at the Gaia archive,
https://gea.esac.esa.int/tap-server/tap.  In particular, it follows
Lindegren's recipes from ESA-SP1200.
We *might* consider for a moment to employ SOFA/ERFA (and hence astropy)
-compatible methods, which take into account secular aberration and use
certain relativistic corrections.  I'd say we shouldn't.  For one,
having secular aberration while assuming linear motions of the objects
is somewhat inconsistent.  Having relativistic corrections results in
differences in the …

Add code for epoch propagation

---

Makefile
expected/init.out
sql/init.sql
src/output.c

Implemented propagation of pg sphere version from Makefile into the code. Fixed pg_sphere_version function.

[ISSUE-10] Implemented propagation of pg sphere version.

---

.travis.yml
Makefile
README.pg_sphere
expected/init_test.out.in
expected/init_test_healpix.out.in
upgrade_scripts/pg_sphere--1.1.5beta4gavo--1.2.0.sql.in
upgrade_scripts/pg_sphere--1.2.0--1.2.1.sql.in
upgrade_scripts/pg_sphere--1.2.1--1.2.2-healpix.sql.in
upgrade_scripts/pg_sphere--1.2.1--1.2.2.sql.in

This PR address issue #19 and makes support for HEALPix/MOC functionality optional. It is enabled by default, but it can be disabled by including `USE_HEALPIX=0` as an argument to the `make` commands. The README.pg_sphere file is updated to reflect this change (and other recent changes to the build process).
Also, when upgrading my installation from 1.2.1 to 1.2.2, I was getting the error:
```
ERROR:  function g_spoint3_fetch(internal, internal, internal) does not exist
```
I've included a fix for that in this PR (the function is just `g_spoint3_fetch(internal)`). Let me know if you prefer that I submit that as a separate PR.

[ISSUE #19] Make HEALPix/MOC support optional

---

README.pg_sphere

There is the first attempt to add some simple description of pgsphere versioning for users. Here we state that the master branch is for development purposes and releases are marked with tags. More detailed explanation of versioning for developers I propose to put into CONTRIBUTING.md.

Added a short description of versioning for users

---

expected/poly.out
sql/poly.sql
src/line.c

The problem fixed by this pull request is described in Issue #35

Fix sline_sline_pos

---

doc/functions.sgm
expected/init_test.out.in
expected/init_test_healpix.out.in
expected/path.out
expected/poly.out
pgs_path.sql.in
pgs_polygon.sql.in
sql/path.sql
sql/poly.sql
src/path.c
src/path.h
src/point.c
src/point.h
src/polygon.c
src/polygon.h
upgrade_scripts/pg_sphere--1.2.3--1.3.0.sql.in

@esabol @vitcpp please, review it.

[ISSUE #16] Implemented a function and tests to extract vertices from spoly by index

---

doc/functions.sgm
expected/init_test.out.in
expected/init_test_healpix.out.in
expected/poly.out
pgs_polygon.sql.in
sql/poly.sql
src/polygon.c
src/polygon.h
upgrade_scripts/pg_sphere--1.2.3--1.3.0.sql.in

Adds function to determine whether the spoly is convex.
Algorithm based on 
https://mathoverflow.net/questions/193569/determining-orientation-of-spherical-polygons

Add spoly_is_convex

---

src/output.c

The variable sphere_output_precision type is changed to int because sprintf requires this argument to be of type int when used as the precision specificator (argument for '*' symbol in the sprintf template).

Fix warnings in output.c

---

src/process_moc.cpp

GCC may produce false warnings in some cases when working with strings (char*) when -Wstringop-overflow is enabled. The patch fixes the compilation warning that origins in some tricky pointers casts.
The error message:
`
g++ -Wall -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wshadow=compatible-local -Wformat-security -fno-strict-aliasing -fwrapv -g -O2 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -DPGSPHERE_VERSION=1.3.1 -I. -I./ -I/home/vit/p.pgsphere/local/include/postgresql/server -I/home/vit/p.pgsphere/local/include/postgresql/internal  -D_GNU_SOURCE  -fopenmp -I/usr/include/healpix_cxx  -c -o src/process_moc.o src/process_moc.cpp -MMD -MP -MF .deps/process_moc.Po
In file included from /usr/include/string.h:535,
from …

Fix compilation error (-Wstringop-overflow)

---

.github/workflows/build-and-check.yml

Use GitHub Actions for pgSphere pipeline. At this moment, builds with HEALPix are failing due to compilation warning, but https://github.com/postgrespro/pgsphere/pull/68 should fix this.

Add GitHub Actions pipeline for pgSphere

---

.github/workflows/deploy-docs.yml

Build and deploy docs to GitHub Pages. This workflow will deploy for master branch. For now, it hosts doc/html directory, so only the last version will be available. How necessary is it to organize the deployment of documentation with previous versions?

Add pipeline for docs using GitHub Pages

---

Makefile

Make evaluates "=" variables lazily, so we can add items to TESTS later in the file and still have them show up in REGRESS.

Maintain only one list of tests

---

.editorconfig

This is the very same .editorconfig file that PostgreSQL is using.
https://github.com/postgres/postgres/commit/ecb09cd5de5279ab9cfa20a58fd3da44f7df5779

Import .editorconfig from PostgreSQL

---

Makefile
doc/indices.sgm
expected/moc_options.out
pgs_moc_ops.sql.in
pgs_moc_options.sql.in
sql/moc_options.sql
src/moc.c
src/pgs_moc.h

Back when smoc GIN indexes were implemented, indexes did not support opclass options yet; that was added only later in PG 13.
Add an "order" parameter on the smoc_gin_ops opclass to allow picking the smoc index granularity between level 0 and 12. (Larger levels do not fit into the internal int32 datatype anymore.)
Example:
`create index on sky using gin (coverage smoc_gin_ops (order = 8))`

Configurable smoc_gin_ops index resolution

---

expected/poly.out
pgs_polygon.sql.in
sql/poly.sql
src/polygon.c
src/polygon.h
upgrade_scripts/pg_sphere--1.3.1--1.3.2.sql.in

As discussed in issue #95, this pull request adds a constructor function to create an spoly from an array of numbers in radians. It is very similar to spoly_deg() except without the calls to `deg_to_rad()`.
Question 1: Can the spoly(float8[]) function be marked PARALLEL SAFE? My reading of the documentation for PARALLEL SAFE doesn't mention anything about accessing arrays or allocating memory, so I think it should be.
Question 2: Can it be marked STRICT? `select spoly(NULL::float8[])` returns null, I believe.
If the answer to either or both questions, I would like to make the same change(s) to `spoly_deg` also.

Add function to create spoly from an array of numbers in radians

---

Makefile
doc/indices.sgm
expected/index.out
pgs_hash.sql.in
sql/index.sql
src/point.c
src/point.h

Besides hash indexes on spoint, this enables "select distinct spoint from tbl" queries.
Close #101.

Hash opclass for spoint

---

src/point.c

Sorry I forgot to test on 32-bit... The new spherepoint_hash32 function crashes on platforms where float8 is passed by pointer.

spherepoint_hash32: float8 needs wrapping into a Datum

---

Makefile

the sparse.c and sscan.c files are now committed in src dir
I use the dist target to create tarballs as part of building rpm packages.

fix Makefile dist target

---

.github/workflows/build-and-check-windows-latest.yml
expected/init_extended.out
sql/init_extended.sql

Add workflow for build and test for MS Windows with USE_HEALPIX = 0 only.

Build and check workflow for MS Windows
